sweepname: !sweep
  values: [1, 2, 3, 4, 5]
othersweep: !sweep 
  values: ["x", "y", "z"]
coupled_sweep: !coupled-sweep
  target: sweepname
  values: [6, 7, 8, 9, 10]
nested:
  a:
    b: !sweep
      values: [11, 12, 13, 14, 15]
    c: x
d: !coupled-sweep
  target: othersweep
  values: ["a", "b", "c"]